// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXd1ffWtPATdTxKXkHxCnlhaBObJB0fTk',
    appId: '1:485695274900:web:a539520df1ac8d5f0c1981',
    messagingSenderId: '485695274900',
    projectId: 'bookstore-346bc',
    authDomain: 'bookstore-346bc.firebaseapp.com',
    storageBucket: 'bookstore-346bc.appspot.com',
    measurementId: 'G-BF11MW7DN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALBttbxUe_dQ6UeDrPy-R_YvWSQt8UVBs',
    appId: '1:485695274900:android:efb44713c014529b0c1981',
    messagingSenderId: '485695274900',
    projectId: 'bookstore-346bc',
    storageBucket: 'bookstore-346bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnaKsNBzXy0wAQS1o85RVg8D2PIqber_8',
    appId: '1:485695274900:ios:c723033c4e3e0c630c1981',
    messagingSenderId: '485695274900',
    projectId: 'bookstore-346bc',
    storageBucket: 'bookstore-346bc.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnaKsNBzXy0wAQS1o85RVg8D2PIqber_8',
    appId: '1:485695274900:ios:c723033c4e3e0c630c1981',
    messagingSenderId: '485695274900',
    projectId: 'bookstore-346bc',
    storageBucket: 'bookstore-346bc.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXd1ffWtPATdTxKXkHxCnlhaBObJB0fTk',
    appId: '1:485695274900:web:05add80c13fe1efe0c1981',
    messagingSenderId: '485695274900',
    projectId: 'bookstore-346bc',
    authDomain: 'bookstore-346bc.firebaseapp.com',
    storageBucket: 'bookstore-346bc.appspot.com',
    measurementId: 'G-9LB9G9KFHB',
  );

}